language: node_js
node_js:
  - "8.10"
script:
  - cd hello-world
  - npm install
  - npm run test
notifications:
  email:
    recipients:
      - jfellman@squareup.com
      - john.fellman@gmail.com
    on_success: always # default: always
    on_failure: always # default: always
