#!/bin/bash

usage() {
  cat<<HERE
  provides easy cli for managing customers through api

  Usage: <command> [args...]

  Commands:
    create <{props...}>   creates a customer, optionally using v1 sandbox
                          props are json encoded

    delete <id>           deletes a customer by id, optionally using v1 sandbox

    list <id>             lists customers, optionally using v1 sandbox
HERE
}

customers-create() {
  echo creating customer...
  echo executing: curl -X POST -H \"Accept: application/json\" -H \"Authorization: Bearer $SQ_ACCESS_TOKEN\" -d \"$1\" \"https://$SQ_HOST/v2/customers\"
  curl -X POST -H "Accept: application/json" -H "Authorization: Bearer $SQ_ACCESS_TOKEN" -d "$1" "https://$SQ_HOST/v2/customers"
  echo
  echo done
}

customers-delete() {
  echo deleting customer...
  echo executing: curl -X DELETE -H \"Authorization: Bearer $SQ_ACCESS_TOKEN\" \"https://$SQ_HOST/v2/customers/$1\"
  curl -X DELETE -H "Authorization: Bearer $SQ_ACCESS_TOKEN" "https://$SQ_HOST/v2/customers/$1"
  echo
  echo done
}

customers-list() {
  echo executing: curl -H \"Authorization: Bearer $SQ_ACCESS_TOKEN\" \"https://$SQ_HOST/v2/customers\"
  curl -H "Authorization: Bearer $SQ_ACCESS_TOKEN" "https://$SQ_HOST/v2/customers"
}

touch /tmp/.sqenv
source /tmp/.sqenv

cmd=$1

# print usage if no command is passed
if [ "$cmd" = "delete" ]; then
  customers-delete $2 $3
elif [ "$cmd" = "list" ]; then
  customers-list $2 $3
elif [ "$cmd" = "create" ]; then
  customers-create $2 $3
else
  usage
fi
